#!/usr/bin/env python

# Copyright (c) 2018 Jeppe Ledet-Pedersen <jlp@satlab.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from __future__ import print_function

import argparse
import crcmod

def crc32c(filename):
    c = crcmod.predefined.mkCrcFun('crc-32c')
    with open(filename, 'rb') as f:
        data = f.read()
        checksum = c(data)

    return checksum, len(data)

def main():
    parser = argparse.ArgumentParser(description='Calculate CRC32C checksum on files.')
    parser.add_argument('files', metavar='FILE', nargs='+', help='File to calculate checksum on')
    args = parser.parse_args()

    for filename in args.files:
        checksum, length = crc32c(filename)
        print('{:08x}  {}  {}'.format(checksum, length, filename))

if __name__ == '__main__':
    main()
